# Generated by Django 3.2.18 on 2023-03-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230319_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredient',
            new_name='ingedients',
        ),
    ]
